services:
- type: web
  name: passthrough
  branch: master
  env: static
  buildCommand: echo "hiya"
  staticPublishPath: ./static/
  autoDeployFilter:
    paths:
    - static/**/*
- type: web
  name: go-server
  branch: master
  env: go
  buildCommand: cd server; go build -o app .; echo "hi"
  startCommand: cd server; ./app
  autoDeployFilter:
    paths:
    - server/*.go
    ignoredPaths:
    - server/**/go.mod
  envVars:
  - key: API_HOST
    fromService:
      name: passthrough
      type: web
      envVarKey: RENDER_EXTERNAL_URL
